### ISSUE TITLE
Adding Fighters

### ISSUE THREAD

**Issue by Muse23PT** [maeligg/unmatcher#2]
Hi,

just want to know if you are planning to keep this tool updated with the new fighters and maps, for example with the new Houdini and Genie fighters and the map that comes with their set?

Also, is there any chance you can also add Deadpool to the list? I see there's already a previous "issue" opened for that but it would be great if you could include it.

Thank you for this awesome tool.

Cheers

**Comment by maeligg** [comment]
Hi, yes I'm planning on updating it as new sets come out. Thanks for reminding me about the open issue, I was missing the card back so now I guess I can add deadpool !

**Comment by Muse23PT** [comment]
Thank you :) 

saw that you also implemented other things that I had suggested when I first saw your app :) 

Cheers
    On Monday, December 5, 2022 at 09:56:13 AM GMT, Maël Brunet ***@***.***> wrote:  
 
 


Hi, yes I'm planning on updating it as new sets come out. Thanks for reminding me about the open issue, I was missing the card back so now I guess I can add deadpool !
